### ISSUE TITLE
Add backdrop shadow to have better contrast between landing page font color and background image.

### ISSUE THREAD

**Issue by adhadse** [gaphor/gaphor.github.io#86]
Currently the background image has many whitish points that doesn't give a good enough contrast with the white font especially for top nav or logo.
![image](https://user-images.githubusercontent.com/56764399/201449124-f0591f48-e162-4914-a4aa-556a6a56645d.png)

Something like:
```css
header.header-front-page {
    background-image: linear-gradient(180deg, #000000 0%, rgba(51, 51, 51, 0.5) 50%), url(/images/splash.jpg);
}
```
To get a much better result:
![image](https://user-images.githubusercontent.com/56764399/201449963-e10edab3-8ea0-4003-a073-a3719e621144.png)
